### PR TITLE
Assets loading

### PR DESCRIPTION
**Pull request by apfelbox**
Allows to load assets (CSS and JavaScript files).

See documentation for all details.

### CODE REVIEW

**Comment by cH40z-Lord** [comment]
Are we supposed to use the two actions via `{{ render(controller(...)) }}`?

**Comment by apfelbox** [comment]
Nope, the changes to `layout.html.twig` were contained in a previous commit by accident: https://github.com/Becklyn/GluggiBundle/commit/e8f6e6db1409c3d3b0317449d119cb337a390197

**Comment by apfelbox** [comment]
All the user has to do is set the config. That's it.

**Comment by cH40z-Lord** [comment]
Why do we need two dedicated controllers to just render the assets includes? Why not solve it with a Twig extension?

**Comment by apfelbox** [comment]
I don't want to clutter the main app with twig function names. As these names aren't namespaced, I only want to expose a single name to the app.

**Pull request merged**
